# Generated by Django 5.2.3 on 2025-06-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique code identifier (e.g. birth, migration)', unique=True)),
                ('label', models.CharField(help_text='Human-readable label (e.g. Birth, Graduation)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description or narrative usage context')),
                ('category', models.CharField(blank=True, help_text='Broad category for grouping (e.g. Life, Spiritual, Migration, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Control availability without deleting')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['category', 'label'],
            },
        ),
    ]
